version: "3.1"

language: en

pipeline:
  - name: SpacyNLP
    model: "en_core_web_md" 
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 150  
    random_seed: 42  
    constrain_similarities: true  
    entity_recognition: true  

policies:
  - name: RulePolicy 
  - name: MemoizationPolicy 
  - name: TEDPolicy
    max_history: 10 
    epochs: 150  

assistant_id: vibesync-2024-final

